version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU28-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD="${MSSQL_SA_PASSWORD}"
    ports:
      - 127.0.0.1:1433:1433
    volumes:
      - /var/opt/mssql:/var/opt/mssql:rw

